# Generated by Django 4.1.2 on 2023-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
