# Generated by Django 4.1.2 on 2023-02-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_student_std_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_img',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
