# Generated by Django 4.1.2 on 2023-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_alter_student_std_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_img',
        ),
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
