# Generated by Django 4.1.1 on 2023-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibraryApp", "0008_alter_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/images/Students/"),
        ),
    ]
